module.exports = {
  weights: {
    keywordRelevance: 0.25,      // Max 25 points
    skillsMatch: 0.20,           // Max 20 points
    jobRelevance: 0.15,          // Max 15 points
    structure: 0.10,             // Max 10 points
    sectionCompleteness: 0.10,   // Max 10 points
    readability: 0.10,           // Max 10 points
    formatting: 0.10             // Max 10 points
  },
  maxScores: {
    keywordRelevance: 25,
    skillsMatch: 20,
    jobRelevance: 15,
    structure: 10,
    sectionCompleteness: 10,
    readability: 10,
    formatting: 10
  },
  disclaimer: "This ATS Compatibility Score is generated by ResumeAI's proprietary evaluation rubric based on industry ATS parsing behaviors. Real applicant tracking systems (such as Workday, Greenhouse, Lever, and Taleo) vary in their exact ranking heuristics."
};
